#ifndef ExploreMasterCONSTRAINT_H_
#define ExploreMaster_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* ExploreMasterCONSTRAINT_H_ */
