#include  "Behaviours/DriveToKitchen1573055193593.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1573055193593) ENABLED START*/
    //Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Behaviour:DriveToKitchen

} /* namespace alica */
