#include  "Behaviours/DriveToHallway1573055349775.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1573055349775) ENABLED START*/
    //Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Behaviour:DriveToHallway

} /* namespace alica */
