#include  "Behaviours/DriveToLab1573055161416.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1573055161416) ENABLED START*/
    //Add additional includes here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Behaviour:DriveToLab

} /* namespace alica */
