#include "Plans/TestPlans/constraints/TestJoystickMaster1531320805154Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1531320805154) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:TestJoystickMaster

/*		
 * Tasks: 
 * - EP:1531320805156 : DefaultTask (1530108941014)
 *
 * States:
 * - Joystick (1531320805155)
 *
 * Vars:
 */

// State: Joystick

// State: Joystick

}
