#include "Plans/Explore1530109132931.h"
using namespace alica;
/*PROTECTED REGION ID(eph1530109132931) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:Explore

    /* generated comment
     
     Task: Explore  -> EntryPoint-ID: 1530109142720

     */
    shared_ptr<UtilityFunction> UtilityFunction1530109132931::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1530109132931) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: Explore in Plan: Explore

}
