#include "Plans/ExploreMaster1530108941003.h"
using namespace alica;
/*PROTECTED REGION ID(eph1530108941003) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:ExploreMaster

/* generated comment

 Task: Explore  -> EntryPoint-ID: 1530108941008

 */
shared_ptr<UtilityFunction> UtilityFunction1530108941003::getUtilityFunction(Plan *plan)
{
    /*PROTECTED REGION ID(1530108941003) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: Explore in Plan: ExploreMaster

} // namespace alicaAutogenerated
