#include "ConditionCreator.h"
#include "StummelMaster1571241152555.h"
#include  "Exploration/Explore1571241166731.h"
#include  "Behaviours/Stop1571238310927.h"
#include  "Behaviours/DriveToLab1573055161416.h"
#include  "Behaviours/DriveToKitchen1573055193593.h"
#include  "Behaviours/DriveToHallway1573055349775.h"
#include  "Behaviours/DriveToOffices1573055365185.h"

using namespace alicaAutogenerated;
namespace alica
{

    ConditionCreator::ConditionCreator()
    {
    }
    ConditionCreator::~ConditionCreator()
    {
    }

    std::shared_ptr<BasicCondition> ConditionCreator::createConditions(long conditionConfId)
    {
        switch (conditionConfId)
        {
            default:
            std::cerr << "ConditionCreator: Unknown condition id requested: " << conditionConfId << std::endl;
            throw new std::exception();
            break;
        }
    }
}
