#include "Stop1571238310927.h"
#include <memory>

/*PROTECTED REGION ID(inccppBC1571238310927) ENABLED START*/
// Addadditionalincludeshere
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {
// Behaviour:Stop

} // namespace alicaAutogenerated
