#include "StummelMaster1570634167988.h"
/*PROTECTED REGION ID(eph1570634167988) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {
// Plan:StummelMaster
/* generated comment
    Task: 1570633373655  -> EntryPoint-ID: 1571238153672
*/
shared_ptr<UtilityFunction>
UtilityFunction1570634167988::getUtilityFunction(Plan *plan) {
  /*PROTECTED REGION ID(1570634167988) ENABLED START*/
  std::shared_ptr<UtilityFunction> defaultFunction =
      std::make_shared<DefaultUtilityFunction>(plan);
  return defaultFunction;
  /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1571238364284, ConditionString: , Comment : start received
 *
 * Plans in State:
 *
 *   - Plan - (Name): 1571238310927, (PlanID): 1571238310927
 *
 * Tasks:
 *
 *   - 1570633373655 (1570633373655) (Entrypoint: 1571238153672)
 *
 * States:
 *
 *   - Stop (1571238161191)
 *   - Start (1571238162554)
 *
 * Vars:
 */
bool PreCondition1571238364284::evaluate(shared_ptr<RunningPlan> rp) {
  /*PROTECTED REGION ID(1571238209115) ENABLED START*/
        return false; //TODO implement me

        /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1571238399899, ConditionString: , Comment : stop received
 *
 * Plans in State:
 *
 *   - Plan - (Name): 1571239218685, (PlanID): 1571239218685
 *
 * Tasks:
 *
 *   - 1570633373655 (1570633373655) (Entrypoint: 1571238153672)
 *
 * States:
 *
 *   - Stop (1571238161191)
 *   - Start (1571238162554)
 *
 * Vars:
 */
bool PreCondition1571238399899::evaluate(shared_ptr<RunningPlan> rp) {
  /*PROTECTED REGION ID(1571238268589) ENABLED START*/
  return false; //TODO implement me
  /*PROTECTED REGION END*/
}
} // namespace alicaAutogenerated
