#include "StummelMaster1571241152555.h"
/*PROTECTED REGION ID(eph1571241152555) ENABLED START*/
//Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Plan:StummelMaster
    /* generated comment
        Task: Default  -> EntryPoint-ID: 1571241176070
    */
    shared_ptr<UtilityFunction> UtilityFunction1571241152555::getUtilityFunction(Plan* plan)
    {
       /*PROTECTED REGION ID(1571241152555) ENABLED START*/
       std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
       return defaultFunction;
        /*PROTECTED REGION END*/
    }
}
