#include "UtilityFunctionCreator.h"
#include <iostream>

#include "Plans/ExploreMaster1530108941003.h"

#include "Plans/Explore1530109132931.h"

#include "Plans/TestPlans/TestJoystickMaster1531320805154.h"

using namespace std;
using namespace alicaAutogenerated;
namespace alica
{

UtilityFunctionCreator::~UtilityFunctionCreator() {}

UtilityFunctionCreator::UtilityFunctionCreator() {}

shared_ptr<BasicUtilityFunction> UtilityFunctionCreator::createUtility(long utilityfunctionConfId)
{
    switch (utilityfunctionConfId)
    {

    case 1530108941003:
        return make_shared<UtilityFunction1530108941003>();
        break;

    case 1530109132931:
        return make_shared<UtilityFunction1530109132931>();
        break;

    case 1531320805154:
        return make_shared<UtilityFunction1531320805154>();
        break;

    default:
        cerr << "UtilityFunctionCreator: Unknown utility requested: " << utilityfunctionConfId << endl;
        throw new exception();
        break;
    }
}

} // namespace alica
