#include "UtilityFunctionCreator.h"
#include "StummelMaster1571241152555.h"
#include  "Exploration/Explore1571241166731.h"
#include <iostream>

using namespace alicaAutogenerated;

namespace alica
{

    UtilityFunctionCreator::~UtilityFunctionCreator()
    {
    }

    UtilityFunctionCreator::UtilityFunctionCreator()
    {
    }


    std::shared_ptr<BasicUtilityFunction> UtilityFunctionCreator::createUtility(long utilityfunctionConfId)
    {
        switch(utilityfunctionConfId)
        {
            case 1571241152555:
                return std::make_shared<UtilityFunction1571241152555>();
                break;
            case 1571241166731:
                return std::make_shared<UtilityFunction1571241166731>();
                break;
            default:
            std::cerr << "UtilityFunctionCreator: Unknown utility requested: " << utilityfunctionConfId << std::endl;
            throw new std::exception();
            break;
        }
    }


}
