#include "Plans/TestPlans/TestJoystickMaster1531320805154.h"
using namespace alica;
/*PROTECTED REGION ID(eph1531320805154) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:TestJoystickMaster

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1531320805156

 */
shared_ptr<UtilityFunction> UtilityFunction1531320805154::getUtilityFunction(Plan *plan)
{
    /*PROTECTED REGION ID(1531320805154) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: Joystick in Plan: TestJoystickMaster

} // namespace alicaAutogenerated
