

#include "DomainCondition.h"
/*PROTECTED REGION ID(incBC1571238310927) ENABLED START*/
// Addadditionalincludeshere
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {
/*PROTECTED REGION ID(meth1571238310927) ENABLED START*/
// Addadditionalincludeshere
/*PROTECTED REGION END*/

} // namespace alicaAutogenerated
