#pragma once

#include "DomainCondition.h"
#include <engine/BasicUtilityFunction.h>
#include <engine/DefaultUtilityFunction.h>
#include <engine/UtilityFunction.h>
/*PROTECTED REGION ID(incl1570634167988) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated {
/*PROTECTED REGION ID(meth1570634167988) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/
class UtilityFunction1570634167988 : public BasicUtilityFunction {
  shared_ptr<UtilityFunction> getUtilityFunction(Plan *plan);
};
class PreCondition1571238364284 : public DomainCondition {
  bool evaluate(std::shared_ptr<RunningPlan> rp);
};
class PreCondition1571238399899 : public DomainCondition {
  bool evaluate(std::shared_ptr<RunningPlan> rp);
};
} // namespace alicaAutogenerated
