#pragma once

#include "DomainCondition.h"
#include <engine/BasicUtilityFunction.h>
#include <engine/DefaultUtilityFunction.h>
#include <engine/UtilityFunction.h>
/*PROTECTED REGION ID(incl1571239990055) ENABLED START*/
// Add additional includes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated {
/*PROTECTED REGION ID(meth1571239990055) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/
class UtilityFunction1571239990055 : public BasicUtilityFunction {
  shared_ptr<UtilityFunction> getUtilityFunction(Plan *plan);
};
} // namespace alicaAutogenerated
