#include "constraints/Stop1571238310927Constraints.h"
/*PROTECTED REGION ID(ch1571238310927) ENABLED START*/
// Addadditionaloptionshere
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {

// Behaviour:Stop
}
