#include "constraints/StummelMaster1570634167988Constraints.h"
/*PROTECTED REGION ID(ch1570634167988) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {
// Plan:StummelMaster
/*
 * Tasks:
 * - EP:1571238153672 : 1570633373655 (1570633373655)
 *
 * States:
 * - Stop (1571238161191)
 * - Start (1571238162554)
 *
 * Vars:
 */

// State: Stop
// State: Start
} // namespace alicaAutogenerated
