#include "constraints/StummelMaster1571241152555Constraints.h"
/*PROTECTED REGION ID(ch1571241152555) ENABLED START*/
        //Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Plan:StummelMaster
    /*
    * Tasks:  
    * - EP:1571241176070 : Default (1570633373655)
    *
    * States: 
    * - Stop (1571241177902)
    * - Start (1571241178465)
    *
    * Vars: 
    */
    
    
    // State: Stop
    // State: Start
}
