#include "constraints/Test1571239990055Constraints.h"
/*PROTECTED REGION ID(ch1571239990055) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {
// Plan:Test
/*
 * Tasks:
 * - EP:1571240000644 : 1570633373655 (1570633373655)
 *
 * States:
 * - Default Name (1571240003546)
 * - Default Name (1571240004404)
 *
 * Vars:
 */

// State: Default Name
// State: Default Name
} // namespace alicaAutogenerated
