#include "Behaviours/constraints/DriveToHallway1573055349775Constraints.h"
/*PROTECTED REGION ID(ch1573055349775) ENABLED START*/
        //Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{

    //Behaviour:DriveToHallway
     
}
