#include "Behaviours/constraints/DriveToKitchen1573055193593Constraints.h"
/*PROTECTED REGION ID(ch1573055193593) ENABLED START*/
        //Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{

    //Behaviour:DriveToKitchen
     
}
