#include "Behaviours/constraints/DriveToLab1573055161416Constraints.h"
/*PROTECTED REGION ID(ch1573055161416) ENABLED START*/
        //Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{

    //Behaviour:DriveToLab
     
}
