#ifndef Explore_H_
#define Explore_H_

#include "DomainCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
#include "engine/UtilityFunction.h"
/*PROTECTED REGION ID(incl1530109132931) ENABLED START*/
// Add includes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1530109132931) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1530109132931 : public BasicUtilityFunction
{
    shared_ptr<UtilityFunction> getUtilityFunction(Plan *plan);
};

} // namespace alicaAutogenerated

#endif
