#ifndef TestJoystickMasterCONSTRAINT_H_
#define TestJoystickMaster_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* TestJoystickMasterCONSTRAINT_H_ */
