#include "Exploration/Explore1571241166731.h"
/*PROTECTED REGION ID(eph1571241166731) ENABLED START*/
//Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Plan:Explore
    /* generated comment
        Task: Default  -> EntryPoint-ID: 1571241343120
    */
    shared_ptr<UtilityFunction> UtilityFunction1571241166731::getUtilityFunction(Plan* plan)
    {
       /*PROTECTED REGION ID(1571241166731) ENABLED START*/
       std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
       return defaultFunction;
        /*PROTECTED REGION END*/
    }
}
