#include "Exploration/Explore1571239218685.h"
/*PROTECTED REGION ID(eph1571239218685) ENABLED START*/
// Addadditionaloptionshere
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {
// Plan:Explore
/* generated comment
    Task: 1570633373655  -> EntryPoint-ID: 1571239239134
*/
shared_ptr<UtilityFunction>
UtilityFunction1571239218685::getUtilityFunction(Plan *plan) {
  /*PROTECTED REGION ID(1571239218685) ENABLED START*/
  std::shared_ptr<UtilityFunction> defaultFunction =
      std::make_shared<DefaultUtilityFunction>(plan);
  return defaultFunction;
  /*PROTECTED REGION END*/
}
} // namespace alicaAutogenerated
