#pragma once

#include "DomainCondition.h"
#include <engine/BasicUtilityFunction.h>
#include <engine/DefaultUtilityFunction.h>
#include <engine/UtilityFunction.h>
/*PROTECTED REGION ID(incl1571239218685) ENABLED START*/
// Addadditionalincludeshere
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated {
/*PROTECTED REGION ID(meth1571239218685) ENABLED START*/
// Addadditionaloptionshere
/*PROTECTED REGION END*/
class UtilityFunction1571239218685 : public BasicUtilityFunction {
  shared_ptr<UtilityFunction> getUtilityFunction(Plan *plan);
};
} // namespace alicaAutogenerated
