#include "Exploration/constraints/Explore1571239218685Constraints.h"
/*PROTECTED REGION ID(ch1571239218685) ENABLED START*/
// Addadditionaloptionshere
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated {
// Plan:Explore
/*
 * Tasks:
 * - EP:1571239239134 : 1570633373655 (1570633373655)
 *
 * States:
 * - DriveToLab (1571239241399)
 * - DriveToMainFloor (1571239264841)
 * - DriveToOffices (1571239269059)
 * - DriveToKitchen (1571239269581)
 *
 * Vars:
 */

// State: DriveToLab
// State: DriveToMainFloor
// State: DriveToOffices
// State: DriveToKitchen
} // namespace alicaAutogenerated
