#include "Exploration/constraints/Explore1571241166731Constraints.h"
/*PROTECTED REGION ID(ch1571241166731) ENABLED START*/
        //Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Plan:Explore
    /*
    * Tasks:  
    * - EP:1571241343120 : Default (1570633373655)
    *
    * States: 
    * - DriveToLab (1571241667090)
    * - DriveToHallway (1571241667604)
    * - DriveToOffices (1571241671453)
    * - DriveToKitchen (1571241672784)
    *
    * Vars: 
    */
    
    
    // State: DriveToLab
    // State: DriveToHallway
    // State: DriveToOffices
    // State: DriveToKitchen
}
