#include "Plans/constraints/Explore1530109132931Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1530109132931) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:Explore

/*		
 * Tasks: 
 * - EP:1530109142720 : Explore (1530108977106)
 *
 * States:
 * - Explore (1530109142719)
 *
 * Vars:
 */

// State: Explore

// State: Explore

}
